Fix edit and destroy bug, will test later
nw0428/tweeter pull request #16
Opened 2017-11-08 01:52 UTC by ericywong

tada!

2017-11-08 01:52 UTC, MSevey commented
i think this is ok at best

2017-11-08 01:53 UTC, nw0428 requested changes
DRY this out please

2017-11-08 01:53 UTC, nw0428 commented on app/views/tweets/index.html.erb
> +        <% if user_signed_in? && (tweet.user_id == current_user.id) %>
This seems like a method that belongs in tweet! Maybe `Tweet#owned_by?(owner)`?

2017-11-08 01:53 UTC, MSevey submitted a review, later dismissed
good, there are more opportunities for links to not show.  go find them

2017-11-08 01:55 UTC, MSevey requested changes
There is another link that should not be seen all the time.  Can't follow yourself

2017-11-08 02:36 UTC, nw0428 approved these changes
AWESOME. Merge away

2017-11-10 14:19 UTC, MSevey approved these changes

2017-11-10 14:19 UTC, merged